development:
  adapter: postgresql
  encoding: unicode
  database: skeleton_development
  pool: 5
  host: localhost
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: skeleton_test
  pool: 5
  username: skeleton
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: skeleton_production
  pool: 5
  username: skeleton
  password:
